name: Notify Lark

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Test Lark
        run: |
          curl -X POST "${{ secrets.LARK_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "msg_type": "text",
            "content": {
              "text": "测试成功 🚀"
            }
          }'
